# Generated by Django 2.0 on 2020-04-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('age', models.CharField(max_length=5, verbose_name='年龄')),
                ('number', models.IntegerField(verbose_name='工号')),
            ],
            options={
                'db_table': 'todo',
            },
        ),
    ]
